/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro přistupnost",contents:"Obsah napovědy. Pro uzavřeni tohoto dialogu stiskněte klavesu ESC.",legend:[{name:"Obecne",items:[{name:"Panel nastrojů editoru",legend:"Stiskněte${toolbarFocus} k prochazeni panelu nastrojů. Přejděte na dalši a předchozi skupiny pomoci TAB a SHIFT-TAB. Přechod na dalši a předchozi tlačitko panelu nastrojů je pomoci ŠIPKA VPRAVO nebo ŠIPKA VLEVO. Stisknutim mezerniku nebo klavesy ENTER tlačitko aktivujete."},{name:"Dialogove okno editoru",
legend:"Uvnitř dialogoveho okna stiskněte TAB pro přesunuti na dalši pole, stiskněte SHIFT + TAB pro přesun na předchozi pole, stiskněte ENTER pro odeslani dialogu, stiskněte ESC pro jeho zrušeni. Pro dialogova okna, ktera maji mnoho karet stiskněte ALT + F10 pr oprochazeni seznamu karet. Pak se přesuňte na dalši kartu pomoci TAB nebo ŠIPKA VPRAVO. Pro přesun na předchozi stiskněte SHIFT + TAB nebo ŠIPKA VLEVO. Stiskněte MEZERNIK nebo ENTER pro vybrani stranky karet."},{name:"Kontextove menu editoru",
legend:"Stiskněte ${contextMenu} nebo klavesu APPLICATION k otevřeni kontextoveho menu. Pak se přesuňte na dalši možnost menu pomoci TAB nebo ŠIPKY DOLŮ. Přesuňte se na předchozi možnost pomoci  SHIFT+TAB nebo ŠIPKY NAHORU. Stiskněte MEZERNIK nebo ENTER pro zvoleni možnosti menu. Podmenu současne možnosti otevřete pomoci MEZERNIKU nebo ENTER či ŠIPKY DOLEVA. Kontextove menu uzavřete stiskem ESC."},{name:"Rameček seznamu editoru",legend:"Uvnitř ramečku seznamu se přesunete na dalši položku menu pomoci TAB nebo ŠIPKA DOLŮ. Na předchozi položku se přesunete SHIFT + TAB nebo ŠIPKA NAHORU. Stiskněte MEZERNIK nebo ENTER pro zvoleni možnosti seznamu. Stiskněte ESC pro uzavřeni seznamu."},
{name:"Lišta cesty prvku v editoru",legend:"Stiskněte ${elementsPathFocus} pro prochazeni lišty cesty prvku. Na dalši tlačitko prvku se přesunete pomoci TAB nebo ŠIPKA VPRAVO. Na předchozi položku se přesunete pomoci SHIFT + TAB nebo ŠIPKA VLEVO. Stiskněte MEZERNIK nebo ENTER pro vybrani prvku v editoru."}]},{name:"Přikazy",items:[{name:" Přikaz Zpět",legend:"Stiskněte ${undo}"},{name:" Přikaz Znovu",legend:"Stiskněte ${redo}"},{name:" Přikaz Tučne",legend:"Stiskněte ${bold}"},{name:" Přikaz Kurziva",
legend:"Stiskněte ${italic}"},{name:" Přikaz Podtrženi",legend:"Stiskněte ${underline}"},{name:" Přikaz Odkaz",legend:"Stiskněte ${link}"},{name:" Přikaz Skryt panel nastrojů",legend:"Stiskněte ${toolbarCollapse}"},{name:"Přikaz pro přistup k předchozimu prostoru zaměřeni",legend:"Stiskněte ${accessPreviousSpace} pro přistup k nejbližšimu nedosažitelnemu prostoru zaměřeni před střiškou, napřiklad: dva přilehle prvky HR. Pro dosaženi vzdalenych prostorů zaměřeni tuto kombinaci klaves opakujte."},{name:"Přikaz pro přistup k dalšimu prostoru zaměřeni",
legend:"Stiskněte ${accessNextSpace} pro přistup k nejbližšimu nedosažitelnemu prostoru zaměřeni po střišce, napřiklad: dva přilehle prvky HR. Pro dosaženi vzdalenych prostorů zaměřeni tuto kombinaci klaves opakujte."},{name:" Napověda přistupnosti",legend:"Stiskněte ${a11yHelp}"}]}]});