/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fi",{title:"Saavutettavuus ohjeet",contents:"Ohjeen sisallot. Sulkeaksesi taman dialogin paina ESC.",legend:[{name:"Yleinen",items:[{name:"Editorin tyokalupalkki",legend:"Paina ${toolbarFocus} siirtyaksesi tyokalupalkkiin. Siirry seuraavaan ja edelliseen tyokalupalkin ryhmaan TAB ja SHIFT-TAB nappaimilla. Siirry seuraavaan ja edelliseen tyokalupainikkeeseen kayttamalla NUOLI OIKEALLE tai NUOLI VASEMMALLE nappaimilla. Paina VALILYONTI tai ENTER nappainta aktivoidaksesi tyokalupainikkeen."},
{name:"Editorin dialogi",legend:"Dialogin sisalla, painamalla TAB siirryt seuraavaan dialogin kenttaan, painamalla SHIFT+TAB siirryt aiempaan kenttaan, painamalla ENTER lahetat dialogin, painamalla ESC peruutat dialogin. Dialogeille joissa on useita valilehtia, paina ALT+F10 siirtyaksesi valillehtilistaan. Siirtyaksesi seuraavaan valilehteen paina TAB tai NUOLI OIKEALLE. Siirry edelliseen valilehteen painamalla SHIFT+TAB tai nuoli vasemmalle. Paina VALILYONTI tai ENTER valitaksesi valilehden."},{name:"Editorin oheisvalikko",
legend:"Paina ${contextMenu} tai SOVELLUSPAINIKETTA avataksesi oheisvalikon. Liiku seuraavaan valikon vaihtoehtoon TAB tai NUOLI ALAS nappaimilla. Siirry edelliseen vaihtoehtoon SHIFT+TAB tai NUOLI YLOS nappaimilla. Paina VALILYONTI tai ENTER valitaksesi valikon kohdan. Avataksesi nykyisen kohdan alivalikon paina VALILYONTI tai ENTER tai NUOLI OIKEALLE painiketta. Siirtyaksesi takaisin valikon ylemmalle tasolle paina ESC tai NUOLI vasemmalle. Oheisvalikko suljetaan ESC painikkeella."},{name:"Editorin listalaatikko",
legend:"Listalaatikon sisalla siirry seuraavaan listan kohtaan TAB tai NUOLI ALAS painikkeilla. Siirry edelliseen listan kohtaan SHIFT+TAB tai NUOLI YLOS painikkeilla. Paina VALILYONTI tai ENTER valitaksesi listan vaihtoehdon. Paina ESC sulkeaksesi listalaatikon."},{name:"Editorin elementtipolun palkki",legend:"Paina ${elementsPathFocus} siirtyaksesi elementtipolun palkkiin. Siirry seuraavaan elementtipainikkeeseen TAB tai NUOLI OIKEALLE painikkeilla. Siirry aiempaan painikkeeseen SHIFT+TAB tai NUOLI VASEMMALLE painikkeilla. Paina VALILYONTI tai ENTER valitaksesi elementin editorissa."}]},
{name:"Komennot",items:[{name:"Peruuta komento",legend:"Paina ${undo}"},{name:"Tee uudelleen komento",legend:"Paina ${redo}"},{name:"Lihavoi komento",legend:"Paina ${bold}"},{name:"Kursivoi komento",legend:"Paina ${italic}"},{name:"Alleviivaa komento",legend:"Paina ${underline}"},{name:"Linkki komento",legend:"Paina ${link}"},{name:"Pienenna tyokalupalkki komento",legend:"Paina ${toolbarCollapse}"},{name:"Siirry aiempaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryaksesi lahimpaan kursorin edella olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkaista HR elementtia. Toista nappainyhdistelmaa paastaksesi kauempana oleviin fokustiloihin."},
{name:"Siirry seuraavaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryaksesi lahimpaan kursorin jalkeen olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkaista HR elementtia. Toista nappainyhdistelmaa paastaksesi kauempana oleviin fokustiloihin."},{name:"Saavutettavuus ohjeet",legend:"Paina ${a11yHelp}"}]}]});