/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr-ca",{title:"Instructions d'accessibilite",contents:"Contenu de l'aide.  Pour fermer cette fenetre, appuyez sur ESC.",legend:[{name:"General",items:[{name:"Barre d'outil de l'editeur",legend:"Appuyer sur ${toolbarFocus} pour acceder a la barre d'outils. Se deplacer vers les groupes suivant ou precedent de la barre d'outil avec les touches TAB et SHIFT-TAB. Se deplacer vers les boutons suivant ou precedent de la barre d'outils avec les touches FLECHE DROITE et FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour activer le bouton de barre d'outils."},
{name:"Dialogue de l'editeur",legend:"A l'interieur d'un dialogue, appuyer sur la touche TAB pour naviguer jusqu'au champ de dalogue suivant, appuyez sur les touches SHIFT + TAB pour revenir au champ precedent, appuyez sur la touche ENTRER pour soumettre le dialogue, appuyer sur la touche ESC pour annuler le dialogue. Pour les dialogues avec plusieurs pages d'onglets, appuyer sur ALT + F10 pour naviguer jusqu'a la liste des onglets. Puis se deplacer vers l'onglet suivant avec la touche TAB ou FLECHE DROITE. Se deplacer vers l'onglet precedent avec les touches SHIFT + TAB ou FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour selectionner la page de l'onglet."},
{name:"Menu contextuel de l'editeur",legend:"Appuyer sur ${contextMenu} ou entrer le RACCOURCI CLAVIER pour ouvrir le menu contextuel. Puis se deplacer vers l'option suivante du menu avec les touches TAB ou FLECHE BAS. Se deplacer vers l'option precedente avec les touches SHIFT+TAB ou FLECHE HAUT. appuyer sur la BARRE D'ESPACE ou la touche ENTREE pour selectionner l'option du menu. Oovrir le sous-menu de l'option courante avec la BARRE D'ESPACE ou les touches ENTREE ou FLECHE DROITE. Revenir a l'element de menu parent avec les touches ESC ou FLECHE GAUCHE. Fermer le menu contextuel avec ESC."},
{name:"Menu deroulant de l'editeur",legend:"A l'interieur d'une liste en menu deroulant, se deplacer vers l'element suivant de la liste avec les touches TAB ou FLECHE BAS. Se deplacer vers l'element precedent de la liste avec les touches SHIFT + TAB ou FLECHE HAUT. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour selectionner l'option dans la liste. Appuyer sur ESC pour fermer le menu deroulant."},{name:"Barre d'emplacement des elements de l'editeur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre d'emplacement des elements de lediteur. Se deplacer vers le bouton d'element suivant avec les touches TAB ou FLECHE DROITE. Se deplacer vers le bouton d'element precedent avec les touches SHIFT+TAB ou FLECHE GAUCHE. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour selectionner l'element dans l'editeur."}]},
{name:"Commandes",items:[{name:"Annuler",legend:"Appuyer sur ${undo}"},{name:"Refaire",legend:"Appuyer sur ${redo}"},{name:"Gras",legend:"Appuyer sur ${bold}"},{name:"Italique",legend:"Appuyer sur ${italic}"},{name:"Souligne",legend:"Appuyer sur ${underline}"},{name:"Lien",legend:"Appuyer sur ${link}"},{name:"Enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Acceder a l'objet de focus precedent",legend:"Appuyer ${accessPreviousSpace} pour acceder au prochain espace disponible avant le curseur, par exemple: deux elements HR adjacents.  Repeter la combinaison pour joindre les elements d'espaces distantes."},
{name:"Acceder au prochain objet de focus",legend:"Appuyer ${accessNextSpace} pour acceder au prochain espace disponible apres le curseur, par exemple: deux elements HR adjacents.  Repeter la combinaison pour joindre les elements d'espaces distantes."},{name:"Aide d'accessibilite",legend:"Appuyer sur ${a11yHelp}"}]}]});