/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","gl",{title:"Instrucions de accesibilidade",contents:"Axuda. Para pechar este dialogo prema ESC.",legend:[{name:"Xeral",items:[{name:"Barra de ferramentas do editor",legend:"Prema ${toolbarFocus} para navegar pola barra de ferramentas. Para moverse polos distintos grupos de ferramentas use as teclas TAB e MAIUS+TAB. Para moverse polas distintas ferramentas use FRECHA DEREITA ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para activar o boton da barra de ferramentas."},
{name:"Editor de dialogo",legend:"Dentro dun cadro de dialogo, prema a tecla TAB para desprazarse ao campo seguinte do cadro de dialogo, prema MAIUS + TAB para desprazarse ao campo anterior, prema INTRO para presentar o cadro de dialogo, prema a tecla ESC para cancelar o dialogo. Para os dialogos que tenen varias paxinas, prema ALT + F10 para navegar a lapela da lista. Despois pasar a seguinte lapela con TAB ou FRECHA DEREITA. Para ir a lapela anterior con SHIFT + TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar a lapela da paxina."},
{name:"Editor do menu contextual",legend:"Prema ${contextMenu} ou a TECLA MENU para abrir o menu contextual. A seguir movase a seguinte opcion do menu con TAB ou FRECHA ABAIXO. Movase a opcion anterior con MAIUS + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para seleccionar a opcion do menu. Abra o submenu da opcion actual con ESPAZO ou INTRO ou FRECHA DEREITA. Regrese ao elemento principal do menu con ESC ou FRECHA ESQUERDA. Peche o menu contextual con ESC."},{name:"Lista do editor",legend:"Dentro dunha lista, movase ao seguinte elemento da lista con TAB ou FRECHA ABAIXO. Movase ao elemento anterior da lista con MAIUS + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para escoller a opcion da lista. Prema ESC para pechar a lista."},
{name:"Barra da ruta ao elemento no editor",legend:"Prema ${elementsPathFocus} para navegar ata os elementos da barra de ruta. Movase ao seguinte elemento boton con TAB ou FRECHA DEREITA. Movase ao boton anterior con MAIUS + TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar o elemento no editor."}]},{name:"Ordes",items:[{name:"Orde «desfacer»",legend:"Prema ${undo}"},{name:"Orde «refacer»",legend:"Prema ${redo}"},{name:"Orde «negra»",legend:"Prema ${bold}"},{name:"Orde «cursiva»",legend:"Prema ${italic}"},
{name:"Orde «sublinar»",legend:"Prema ${underline}"},{name:"Orde «ligazon»",legend:"Prema ${link}"},{name:"Orde «contraer a barra de ferramentas»",legend:"Prema ${toolbarCollapse}"},{name:"Orde «acceder ao anterior espazo en foco»",legend:"Prema ${accessPreviousSpace} para acceder ao espazo mais proximo de foco inalcanzabel anterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinacion de teclas para chegar a espazos de foco distantes."},{name:"Orde «acceder ao seguinte espazo en foco»",
legend:"Prema ${accessNextSpace} para acceder ao espazo mais proximo de foco inalcanzabel posterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinacion de teclas para chegar a espazos de foco distantes."},{name:"Axuda da accesibilidade",legend:"Prema ${a11yHelp}"}]}]});