/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"Kisegitő utasitasok",contents:"Sugo tartalmak. A parbeszedablak bezarasahoz nyomjon ESC-et.",legend:[{name:"Altalanos",items:[{name:"Szerkesztő Eszkoztar",legend:"Nyomjon ${toolbarFocus} hogy kijelolje az eszkoztarat. A kovetkező es előző eszkoztar csoporthoz a TAB es SHIFT TAB-al juthat el. A kovetkező es előző eszkoztar gombhoz a BAL NYIL vagy JOBB NYIL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktivalja az eszkoztar gombot."},{name:"Szerkesző parbeszed ablak",
legend:"Parbeszedablakban nyomjon TAB-ot a kovetkező parbeszedmezőhoz ugrashoz, nyomjon SHIFT + TAB-ot az előző mezőhoz ugrashoz, nyomjon ENTER-t a parbeszedablak elfogadasahoz, nyomjon ESC-et a parbeszedablak elvetesehez. Azokhoz a parbeszedablakokhoz, amik tobb fulet tartalmaznak, nyomjon ALT + F10-et hogy a fulekre ugorjon. Ezutan a TAB-al vagy a JOBB NYILLAL a kovetkező fulre ugorhat. Az előző fulre ugrashoz hasznalja a SHIFT + TAB-ot vagy a BAL NYILAT. Nyomjon SPACE-t vagy ENTER-t hogy kijelolje a fulet."},
{name:"Szerkesztő helyi menu",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZAS BILLENTYŰT a helyi menu megnyitasahoz. Ezutan a kovetkező menupontra lephet a TAB vagy LEFELE NYILLAL. Az előző opciot a SHIFT+TAB vagy FELFELE NYILLAL erheti el. Nyomjon SPACE-t vagy ENTER-t a menupont kivalasztasahoz. A jelenlegi menupont almenujenek megnyitasahoz nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A főmenuhoz valo visszatereshez nyomjon ESC-et vagy BAL NYILAT. A helyi menu bezarasa az ESC billentyűvel lehetseges."},
{name:"Szerkesztő lista",legend:"A listan belul a kovetkező elemre a TAB vagy LEFELE NYILLAL mozoghat. Az előző elem kivalasztasahoz nyomjon SHIFT+TAB-ot vagy FELFELE NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kivalasztasahoz. Az ESC billentyű megnyomasaval bezarhatja a listat."},{name:"Szerkesztő elem utak sav",legend:"Nyomj ${elementsPathFocus} hogy kijelold a elemek ut savjat. A kovetkező elem gombhoz a TAB-al vagy a JOBB NYILLAL juthatsz el. Az előző gombhoz a SHIFT+TAB vagy BAL NYILLAL mehetsz. A SPACE vagy ENTER billentyűvel kivalaszthatod az elemet a szerkesztőben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonasa",legend:"Nyomj ${undo}"},{name:"Parancs megismetlese",legend:"Nyomjon ${redo}"},{name:"Felkover parancs",legend:"Nyomjon ${bold}"},{name:"Dőlt parancs",legend:"Nyomjon ${italic}"},{name:"Alahuzott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"Szerkesztősav osszecsukasa parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"Hozzaferes az előző fokusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzaferj a legkozelebbi elerhetetlen fokusz helyhez a hianyjel előtt, peldaul: ket szomszedos HR elemhez. Ismeteld meg a billentyűkombinaciot hogy megtalald a tavolabbi fokusz helyeket."},
{name:"Hozzaferes a kovetkező fokusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzaferj a legkozelebbi elerhetetlen fokusz helyhez a hianyjel utan, peldaul: ket szomszedos HR elemhez. Ismeteld meg a billentyűkombinaciot hogy megtalald a tavolabbi fokusz helyeket."},{name:"Kisegitő sugo",legend:"Nyomjon ${a11yHelp}"}]}]});