/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt",{title:"Instrucoes de Acessibilidade",contents:"Conteudos da Ajuda. Pressione em 'ESC' para fechar esta janela.",legend:[{name:"Geral",items:[{name:"Barra de Ferramentas do Editor",legend:"Clique em ${toolbarFocus} para navegar para a barra de ferramentas. Va para o grupo da barra de ferramentas anterior e seguinte com TAB e SHIFT+TAB. Va para o botao da barra de ferramentas anterior com a SETA DIREITA ou ESQUERDA. Pressione ESPACO ou ENTER para ativar o botao da barra de ferramentas."},
{name:"Janela do Editor",legend:"Dentro de uma janela, pressione TAB para navigar para o campo da janela seguinte, pressione SHIFT + TAB para mover para o campo anterior, pressione ENTER para submeter a janela, pressione ESC para cancelar a janela. Para as janelas que tem multiplos paginas com separadores, pressione ALT + F10 para navegar para a lista do separador. Depois mova para o seguinte separador com TAB ou SETA DIREITA. Mover para o separador anterior com SHIFT + TAB ou SETA ESQUERDA. Pressione ESPACO ou ENTER para selecionar o separador da pagina."},
{name:"Menu de Contexto do Editor",legend:"Clique em ${contextMenu} ou TECLA APLICACAO para abrir o menu de contexto. Depois va para a opcao do menu seguinte com TAB ou SETA PARA BAIXO. Va para a opcao anterior com  SHIFT+TAB ou SETA PARA CIMA. Pressione ESPACO ou ENTER para selecionar a opcao do menu.  Abra o submenu da opcao atual com ESPACO, ENTER ou SETA DIREITA. GVa para o item do menu parente  com ESC ou SETA ESQUERDA. Feche o menu de contexto com ESC."},{name:"Caixa Lista Editor",legend:"Dentro da caixa da lista, va para o itemda lista seguinte com TAB ou SETA PARA BAIXO. Move Va parao item da lista anterior com SHIFT+TAB ou SETA PARA BAIXO. Pressione ESPACO ou ENTER para selecionar a opcao da lista. Pressione ESC para fechar a caisa da lista."},
{name:"Caminho Barra Elemento Editor",legend:"Clique em ${elementsPathFocus} para navegar para a barra do caminho dos elementos. Va para o botao do elemento seguinte com TAB ou SETA DIREITA. Va para o botao anterior com   SHIFT+TAB ou SETA ESQUERDA. Pressione ESPACO ou ENTER para selecionar o elemento no editor."}]},{name:"Comandos",items:[{name:"Comando de Anular",legend:"Pressione ${undo}"},{name:"Comando de Refazer",legend:"Pressione ${redo}"},{name:"Comando de Negrito",legend:"Pressione ${bold}"},
{name:"Comando de Italico",legend:"Pressione ${italic}"},{name:"Comando de Sublinhado",legend:"Pressione ${underline}"},{name:"Comando de Hiperligacao",legend:"Pressione ${link}"},{name:"Comando de Ocultar Barra de Ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Acesso comando do espaco focus anterior",legend:"Clique em ${accessPreviousSpace} para aceder ao espaco do focos inalcancavel mais perto antes do sinal de omissao, por exemplo: dois elementos HR adjacentes. Repetir a combinacao da chave para alcancar os espacos dos focos distantes."},
{name:"Acesso comando do espaco focus seguinte",legend:"Pressione ${accessNextSpace} para aceder ao espaco do focos inalcancavel mais perto depois do sinal de omissao, por exemplo: dois elementos HR adjacentes. Repetir a combinacao da chave para alcancar os espacos dos focos distantes."},{name:"Ajuda de Acessibilidade",legend:"Pressione ${a11yHelp}"}]}]});