/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"Inštrukcie pristupnosti",contents:"Pomocny obsah. Pre zatvorenie tohto okna, stlačte ESC.",legend:[{name:"Všeobecne",items:[{name:"Lišta nastrojov editora",legend:"Stlačte ${toolbarFocus} pre navigaciu na lištu nastrojov. Medzi ďalšou a predchadzajucou lištou nastrojov sa pohybujete s TAB a SHIFT-TAB. Medzi ďalšim a predchadzajucim tlačidlom na lište nastrojov sa pohybujete s pravou šipkou a ľavou šipkou. Stlačte medzernik alebo ENTER pre aktivaciu tlačidla lišty nastrojov."},
{name:"Editorovy dialog",legend:"V dialogu, stlačte TAB pre navigaciu na ďalšie dialogove pole, stlačte STIFT + TAB pre presun na predchadzajuce pole, stlačte ENTER pre odoslanie dialogu, stlačte ESC pre zrušenie dialogu. Pre dialogy, ktore maju viac založiek, stlačte ALT + F10 pre navigacou do zoznamu založiek. Potom sa posuvajte k ďalšej žaložke pomocou TAB alebo pravou šipkou. Pre presun k predchadzajucej založke, stlačte SHIFT + TAB alebo ľavu šipku. Stlačte medzernik alebo ENTER pre vybranie založky."},
{name:"Editorove kontextove menu",legend:"Stlačte ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextoveho menu. Potom sa presuvajte na ďalšie možnosti menu s TAB alebo dolnou šipkou. Presunte sa k predchadzajucej možnosti s SHIFT + TAB alebo hornou šipkou. Stlačte medzernik alebo ENTER pre vyber možnosti menu. Otvorte pod-menu danej možnosti s medzernikom, alebo ENTER, alebo pravou šipkou. Vraťte sa spať do položky rodičovskeho menu s ESC alebo ľavou šipkou. Zatvorte kontextove menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presuňte sa na ďalšiu položku v zozname s TAB alebo dolnou šipkou. Presuňte sa k predchadzajucej položke v zozname so SHIFT + TAB alebo hornou šipkou. Stlačte medzernik alebo ENTER pre vyber možnosti zoznamu. Stlačte ESC pre zatvorenie boxu zoznamu."},{name:"Editorove pasmo cesty prvku",legend:"Stlačte ${elementsPathFocus} pre navigovanie na pasmo cesty elementu. Presuňte sa na tlačidlo ďalšieho prvku s TAB alebo pravou šipkou. Presuňte sa k predchadzajucemu tlačidlu s SHIFT + TAB alebo ľavou šipkou. Stlačte medzernik alebo ENTER pre vyber prvku v editore."}]},
{name:"Prikazy",items:[{name:"Vratiť prikazy",legend:"Stlačte ${undo}"},{name:"Nanovo vratiť prikaz",legend:"Stlačte ${redo}"},{name:"Prikaz na stučnenie",legend:"Stlačte ${bold}"},{name:"Prikaz na kurzivu",legend:"Stlačte ${italic}"},{name:"Prikaz na podčiarknutie",legend:"Stlačte ${underline}"},{name:"Prikaz na odkaz",legend:"Stlačte ${link}"},{name:"Prikaz na zbalenie lišty nastrojov",legend:"Stlačte ${toolbarCollapse}"},{name:"Prejsť na predchadzajucu zamerateľnu medzeru prikazu",legend:"Stlačte ${accessPreviousSpace} pre pristup na najbližšie nedosiahnuteľne zamerateľne medzery pred vsuvkuo. Napriklad: dve za sebou iduce horizontalne čiary. Opakujte kombinaciu klavesov pre dosiahnutie vzdialenych zamerateľnych medzier."},
{name:"Prejsť na ďalši ",legend:"Stlačte ${accessNextSpace} pre pristup na najbližšie nedosiahnuteľne zamerateľne medzery po vsuvke. Napriklad: dve za sebou iduce horizontalne čiary. Opakujte kombinaciu klavesov pre dosiahnutie vzdialenych zamerateľnych medzier."},{name:"Pomoc pristupnosti",legend:"Stlačte ${a11yHelp}"}]}]});