/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"Hjalpmedelsinstruktioner",contents:"Hjalpinnehall. For att stanga denna dialogruta trycker du pa ESC.",legend:[{name:"Allmant",items:[{name:"Editor verktygsfalt",legend:"Tryck pa ${toolbarFocus} for att navigera till verktygsfaltet. Flytta till nasta och foregaende verktygsfaltsgrupp med TAB och SHIFT-TAB. Flytta till nasta och foregaende knapp i verktygsfaltet med HOGERPIL eller VANSTERPIL. Tryck Space eller ENTER for att aktivera knappen i verktygsfaltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB for att navigera till nasta falt i dialogrutan. Du trycker SKIFT + TAB for att flytta till foregaende falt. Tryck ENTER for att skicka. Du avbryter och stanger dialogen med ESC. For dialogrutor som har flera flikar, tryck ALT + F10 navigera till fliklistan. Flytta sedan till nasta flik med HOGERPIL. Flytta till foregaende flik med SHIFT + TAB eller VANSTERPIL. Tryck Space eller ENTER for att valja fliken."},{name:"Editor for innehallsmeny",
legend:"Tryck pa $ {contextMenu} eller PROGRAMTANGENTEN for att oppna snabbmenyn. Flytta sedan till nasta menyalternativ med TAB eller NEDPIL. Flytta till foregaende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER for att valja menyalternativ. Oppna undermeny av nuvarande alternativ med SPACE eller ENTER eller HOGERPIL. Ga tillbaka till overordnade menyalternativ med ESC eller VANSTERPIL. Stang snabbmenyn med ESC."},{name:"Editor for List Box",legend:"Inuti en list-box, ga till nasta listobjekt med TAB eller NEDPIL. Flytta till foregaende listobjekt med SHIFT + TAB eller UPPIL. Tryck Space eller ENTER for att valja listan alternativet. Tryck ESC for att stanga listan-boxen."},
{name:"Editor for elementens sokvag",legend:"Tryck pa $ {elementsPathFocus} for att navigera till verktygsfaltet for elementens sokvagar. Flytta till nasta elementknapp med TAB eller HOGERPIL. Flytta till foregaende knapp med SKIFT + TAB eller VANSTERPIL. Tryck Space eller ENTER for att valja element i redigeraren."}]},{name:"Kommandon",items:[{name:"Kommandot angra",legend:"Tryck pa ${undo}"},{name:"Kommandot gor om",legend:"Tryck pa ${redo}"},{name:"Kommandot fet stil",legend:"Tryck pa ${bold}"},
{name:"Kommandot kursiv",legend:"Tryck pa ${italic}"},{name:"Kommandot understruken",legend:"Tryck pa ${underline}"},{name:"kommandot lank",legend:"Tryck pa ${link}"},{name:"Verktygsfalt Dolj kommandot",legend:"Tryck pa ${toolbarCollapse}"},{name:"Ga till foregaende fokus plats",legend:"Tryck pa ${accessPreviousSpace} for att ga till narmast onabara utrymme fore markoren, exempel: tva intilliggande HR element. Repetera tangentkombinationen for att ga till nasta."},{name:"Tillga nasta fokuskommandots utrymme",
legend:"Tryck ${accessNextSpace} pa for att komma at den narmaste onabar fokus utrymme efter cirkumflex, till exempel: tva intilliggande HR element. Upprepa tangentkombinationen for att na avlagsna fokus utrymmen."},{name:"Hjalp om tillganglighet",legend:"Tryck ${a11yHelp}"}]}]});