/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"Erişilebilirlik Talimatları",contents:"Yardım iceriği. Bu pencereyi kapatmak icin ESC tuşuna basın.",legend:[{name:"Genel",items:[{name:"Duzenleyici Arac Cubuğu",legend:"Arac cubuğunda gezinmek icin ${toolbarFocus} basın. TAB ve SHIFT-TAB ile onceki ve sonraki arac cubuğu grubuna taşıyın. SAĞ OK veya SOL OK ile onceki ve sonraki bir arac cubuğu duğmesini hareket ettirin. SPACE tuşuna basın veya arac cubuğu duğmesini etkinleştirmek icin ENTER tuşna basın."},
{name:"Diyalog Duzenleyici",legend:"Dialog penceresi icinde, sonraki iletişim alanına gitmek icin SEKME tuşuna basın, onceki alana gecmek icin SHIFT + TAB tuşuna basın, pencereyi gondermek icin ENTER tuşuna basın, dialog penceresini iptal etmek icin ESC tuşuna basın. Birden cok sekme sayfaları olan diyalogların, sekme listesine gitmek icin ALT + F10 tuşlarına basın. Sonra TAB veya SAĞ OK sonraki sekmeye taşıyın. SHIFT + TAB veya SOL OK ile onceki sekmeye gecin. Sekme sayfayı secmek icin SPACE veya ENTER tuşuna basın."},
{name:"İcerik Menu Editoru",legend:"İcerik menusunu acmak icin ${contextMenu} veya UYGULAMA TUŞU'na basın. Daha sonra SEKME veya AŞAĞI OK ile bir sonraki menu seceneği taşıyın. SHIFT + TAB veya YUKARI OK ile onceki seceneğe gider. Menu seceneğini secmek icin SPACE veya ENTER tuşuna basın. Secili seceneğin alt menusunu SPACE ya da ENTER veya SAĞ OK acın. Ust menu oğesini gecmek icin ESC veya SOL OK ile geri donun. ESC ile bağlam menusunu kapatın."},{name:"Liste Kutusu Editoru",legend:"Liste kutusu icinde, bir sonraki liste oğesine SEKME VEYA AŞAĞI OK ile taşıyın. SHIFT + TAB veya YUKARI onceki liste oğesi taşıyın. Liste seceneği secmek icin SPACE veya ENTER tuşuna basın. Liste kutusunu kapatmak icin ESC tuşuna basın."},
{name:"Element Yol Cubuğu Editoru",legend:"Elementlerin yol cubuğunda gezinmek icin ${ElementsPathFocus} basın. SEKME veya SAĞ OK ile sonraki element duğmesine taşıyın. SHIFT + TAB veya SOL OK onceki duğmeye hareket ettirin. Editor icindeki elementi secmek icin ENTER veya SPACE tuşuna basın."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya basın"},{name:"Komutu geri al",legend:"${redo} basın"},{name:" Kalın komut",legend:"${bold} basın"},{name:" İtalik komutu",legend:"${italic} basın"},
{name:" Alttan cizgi komutu",legend:"${underline} basın"},{name:" Bağlantı komutu",legend:"${link} basın"},{name:" Arac cubuğu Toplama komutu",legend:"${toolbarCollapse} basın"},{name:"Onceki komut alanına odaklan",legend:"Duzeltme imlecinden once, en yakın uzaktaki alana erişmek icin ${accessPreviousSpace} basın, orneğin: iki birleşik HR elementleri. Aynı tuş kombinasyonu tekrarıyla diğer alanlarada ulaşın."},{name:"Sonraki komut alanına odaklan",legend:"Duzeltme imlecinden sonra, en yakın uzaktaki alana erişmek icin ${accessNextSpace} basın, orneğin: iki birleşik HR elementleri. Aynı tuş kombinasyonu tekrarıyla diğer alanlarada ulaşın."},
{name:"Erişilebilirlik Yardımı",legend:"${a11yHelp}'e basın"}]}]});