/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak eura",lsquo:"Počatečni uvozovka jednoducha",rsquo:"Koncova uvozovka jednoducha",ldquo:"Počatečni uvozovka dvojita",rdquo:"Koncova uvozovka dvojita",ndash:"En pomlčka",mdash:"Em pomlčka",iexcl:"Obraceny vykřičnik",cent:"Znak centu",pound:"Znak libry",curren:"Znak měny",yen:"Znak jenu",brvbar:"Přerušena svisla čara",sect:"Znak oddilu",uml:"Přehlaska",copy:"Znak copyrightu",ordf:"Žensky indikator rodu",laquo:"Znak dvojitych lomenych uvozovek vlevo",
not:"Logisticky zapor",reg:"Znak registrace",macr:"Pomlčka nad",deg:"Znak stupně",sup2:"Dvojka jako horni index",sup3:"Trojka jako horni index",acute:"Čarka nad vpravo",micro:"Znak mikro",para:"Znak odstavce",middot:"Tečka uprostřed",cedil:"Ocasek vlevo",sup1:"Jednička jako horni index",ordm:"Mužsky indikator rodu",raquo:"Znak dvojitych lomenych uvozovek vpravo",frac14:"Obyčejny zlomek jedna čtvrtina",frac12:"Obyčejny zlomek jedna polovina",frac34:"Obyčejny zlomek tři čtvrtiny",iquest:"Znak obraceneho otazniku",
Agrave:"Velke pismeno latinky A s čarkou nad vlevo",Aacute:"Velke pismeno latinky A s čarkou nad vpravo",Acirc:"Velke pismeno latinky A s vokaněm",Atilde:"Velke pismeno latinky A s tildou",Auml:"Velke pismeno latinky A s dvěma tečkami",Aring:"Velke pismeno latinky A s kroužkem nad",AElig:"Velke pismeno latinky Ae",Ccedil:"Velke pismeno latinky C s ocaskem vlevo",Egrave:"Velke pismeno latinky E s čarkou nad vlevo",Eacute:"Velke pismeno latinky E s čarkou nad vpravo",Ecirc:"Velke pismeno latinky E s vokaněm",
Euml:"Velke pismeno latinky E s dvěma tečkami",Igrave:"Velke pismeno latinky I s čarkou nad vlevo",Iacute:"Velke pismeno latinky I s čarkou nad vpravo",Icirc:"Velke pismeno latinky I s vokaněm",Iuml:"Velke pismeno latinky I s dvěma tečkami",ETH:"Velke pismeno latinky Eth",Ntilde:"Velke pismeno latinky N s tildou",Ograve:"Velke pismeno latinky O s čarkou nad vlevo",Oacute:"Velke pismeno latinky O s čarkou nad vpravo",Ocirc:"Velke pismeno latinky O s vokaněm",Otilde:"Velke pismeno latinky O s tildou",
Ouml:"Velke pismeno latinky O s dvěma tečkami",times:"Znak nasobeni",Oslash:"Velke pismeno latinky O přeškrtnute",Ugrave:"Velke pismeno latinky U s čarkou nad vlevo",Uacute:"Velke pismeno latinky U s čarkou nad vpravo",Ucirc:"Velke pismeno latinky U s vokaněm",Uuml:"Velke pismeno latinky U s dvěma tečkami",Yacute:"Velke pismeno latinky Y s čarkou nad vpravo",THORN:"Velke pismeno latinky Thorn",szlig:"Male pismeno latinky ostre s",agrave:"Male pismeno latinky a s čarkou nad vlevo",aacute:"Male pismeno latinky a s čarkou nad vpravo",
acirc:"Male pismeno latinky a s vokaněm",atilde:"Male pismeno latinky a s tildou",auml:"Male pismeno latinky a s dvěma tečkami",aring:"Male pismeno latinky a s kroužkem nad",aelig:"Male pismeno latinky ae",ccedil:"Male pismeno latinky c s ocaskem vlevo",egrave:"Male pismeno latinky e s čarkou nad vlevo",eacute:"Male pismeno latinky e s čarkou nad vpravo",ecirc:"Male pismeno latinky e s vokaněm",euml:"Male pismeno latinky e s dvěma tečkami",igrave:"Male pismeno latinky i s čarkou nad vlevo",iacute:"Male pismeno latinky i s čarkou nad vpravo",
icirc:"Male pismeno latinky i s vokaněm",iuml:"Male pismeno latinky i s dvěma tečkami",eth:"Male pismeno latinky eth",ntilde:"Male pismeno latinky n s tildou",ograve:"Male pismeno latinky o s čarkou nad vlevo",oacute:"Male pismeno latinky o s čarkou nad vpravo",ocirc:"Male pismeno latinky o s vokaněm",otilde:"Male pismeno latinky o s tildou",ouml:"Male pismeno latinky o s dvěma tečkami",divide:"Znak děleni",oslash:"Male pismeno latinky o přeškrtnute",ugrave:"Male pismeno latinky u s čarkou nad vlevo",
uacute:"Male pismeno latinky u s čarkou nad vpravo",ucirc:"Male pismeno latinky u s vokaněm",uuml:"Male pismeno latinky u s dvěma tečkami",yacute:"Male pismeno latinky y s čarkou nad vpravo",thorn:"Male pismeno latinky thorn",yuml:"Male pismeno latinky y s dvěma tečkami",OElig:"Velka ligatura latinky OE",oelig:"Mala ligatura latinky OE",372:"Velke pismeno latinky W s vokaněm",374:"Velke pismeno latinky Y s vokaněm",373:"Male pismeno latinky w s vokaněm",375:"Male pismeno latinky y s vokaněm",sbquo:"Dolni 9 uvozovka jednoducha",
8219:"Horni obracena 9 uvozovka jednoducha",bdquo:"Dolni 9 uvozovka dvojita",hellip:"Trojtečkovy uvod",trade:"Obchodni značka",9658:"Černy ukazatel směřujici vpravo",bull:"Kolečko",rarr:"Šipka vpravo",rArr:"Dvojita šipka vpravo",hArr:"Dvojita šipka vlevo a vpravo",diams:"Černe piky",asymp:"Teměř se rovna"});