/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","es",{euro:"Simbolo de euro",lsquo:"Comilla simple izquierda",rsquo:"Comilla simple derecha",ldquo:"Comilla doble izquierda",rdquo:"Comilla doble derecha",ndash:"Guion corto",mdash:"Guion medio largo",iexcl:"Signo de admiracion invertido",cent:"Simbolo centavo",pound:"Simbolo libra",curren:"Simbolo moneda",yen:"Simbolo yen",brvbar:"Barra vertical rota",sect:"Simbolo seccion",uml:"Dieresis",copy:"Signo de derechos de autor",ordf:"Indicador ordinal femenino",laquo:"Abre comillas angulares",
not:"Signo negacion",reg:"Signo de marca registrada",macr:"Guion alto",deg:"Signo de grado",sup2:"Superindice dos",sup3:"Superindice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"Superindice uno",ordm:"Indicador orginal masculino",raquo:"Cierra comillas angulares",frac14:"Fraccion ordinaria de un quarto",frac12:"Fraccion ordinaria de una mitad",frac34:"Fraccion ordinaria de tres cuartos",iquest:"Signo de interrogacion invertido",Agrave:"Letra A latina mayuscula con acento grave",
Aacute:"Letra A latina  mayuscula con acento agudo",Acirc:"Letra A latina mayuscula con acento circunflejo",Atilde:"Letra A latina mayuscula con tilde",Auml:"Letra A latina mayuscula con dieresis",Aring:"Letra A latina mayuscula con aro arriba",AElig:"Letra A latina mayuscula",Ccedil:"Letra C latina mayuscula con cedilla",Egrave:"Letra E latina mayuscula con acento grave",Eacute:"Letra E latina mayuscula con acento agudo",Ecirc:"Letra E latina mayuscula con acento circunflejo",Euml:"Letra E latina mayuscula con dieresis",
Igrave:"Letra I latina mayuscula con acento grave",Iacute:"Letra I latina mayuscula con acento agudo",Icirc:"Letra I latina mayuscula con acento circunflejo",Iuml:"Letra I latina mayuscula con dieresis",ETH:"Letra Eth latina mayuscula",Ntilde:"Letra N latina mayuscula con tilde",Ograve:"Letra O latina mayuscula con acento grave",Oacute:"Letra O latina mayuscula con acento agudo",Ocirc:"Letra O latina mayuscula con acento circunflejo",Otilde:"Letra O latina mayuscula con tilde",Ouml:"Letra O latina mayuscula con dieresis",
times:"Signo de multiplicacion",Oslash:"Letra O latina mayuscula con barra inclinada",Ugrave:"Letra U latina mayuscula con acento grave",Uacute:"Letra U latina mayuscula con acento agudo",Ucirc:"Letra U latina mayuscula con acento circunflejo",Uuml:"Letra U latina mayuscula con dieresis",Yacute:"Letra Y latina mayuscula con acento agudo",THORN:"Letra Thorn latina mayuscula",szlig:"Letra s latina fuerte pequena",agrave:"Letra a latina pequena con acento grave",aacute:"Letra a latina pequena con acento agudo",
acirc:"Letra a latina pequena con acento circunflejo",atilde:"Letra a latina pequena con tilde",auml:"Letra a latina pequena con dieresis",aring:"Letra a latina pequena con aro arriba",aelig:"Letra a latina pequena",ccedil:"Letra c latina pequena con cedilla",egrave:"Letra e latina pequena con acento grave",eacute:"Letra e latina pequena con acento agudo",ecirc:"Letra e latina pequena con acento circunflejo",euml:"Letra e latina pequena con dieresis",igrave:"Letra i latina pequena con acento grave",
iacute:"Letra i latina pequena con acento agudo",icirc:"Letra i latina pequena con acento circunflejo",iuml:"Letra i latina pequena con dieresis",eth:"Letra eth latina pequena",ntilde:"Letra n latina pequena con tilde",ograve:"Letra o latina pequena con acento grave",oacute:"Letra o latina pequena con acento agudo",ocirc:"Letra o latina pequena con acento circunflejo",otilde:"Letra o latina pequena con tilde",ouml:"Letra o latina pequena con dieresis",divide:"Signo de division",oslash:"Letra o latina minuscula con barra inclinada",
ugrave:"Letra u latina pequena con acento grave",uacute:"Letra u latina pequena con acento agudo",ucirc:"Letra u latina pequena con acento circunflejo",uuml:"Letra u latina pequena con dieresis",yacute:"Letra u latina pequena con acento agudo",thorn:"Letra thorn latina minuscula",yuml:"Letra y latina pequena con dieresis",OElig:"Diptongo OE latino en mayuscula",oelig:"Diptongo oe latino en minuscula",372:"Letra W latina mayuscula con acento circunflejo",374:"Letra Y latina mayuscula con acento circunflejo",
373:"Letra w latina pequena con acento circunflejo",375:"Letra y latina pequena con acento circunflejo",sbquo:"Comilla simple baja-9",8219:"Comilla simple alta invertida-9",bdquo:"Comillas dobles bajas-9",hellip:"Puntos suspensivos horizontales",trade:"Signo de marca registrada",9658:"Apuntador negro apuntando a la derecha",bull:"Vineta",rarr:"Flecha a la derecha",rArr:"Flecha doble a la derecha",hArr:"Flecha izquierda derecha doble",diams:"Diamante negro",asymp:"Casi igual a"});