/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr-ca",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret",iexcl:"Point d'exclamation inverse",cent:"Symbole de cent",pound:"Symbole de Livre Sterling",curren:"Symbole monetaire",yen:"Symbole du Yen",brvbar:"Barre scindee",sect:"Symbole de section",uml:"Trema",copy:"Symbole de copyright",ordf:"Indicateur ordinal feminin",laquo:"Guillemet francais ouvrant",
not:"Indicateur de negation",reg:"Symbole de marque deposee",macr:"Macron",deg:"Degre",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aigue",micro:"Symbole micro",para:"Paragraphe",middot:"Point median",cedil:"Cedille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet francais fermant",frac14:"Un quart",frac12:"Une demi",frac34:"Trois quart",iquest:"Point d'interrogation inverse",Agrave:"A accent grave",Aacute:"A accent aigue",Acirc:"A circonflexe",Atilde:"A tilde",Auml:"A trema",
Aring:"A avec un rond au dessus",AElig:"A majuscule",Ccedil:"C cedille",Egrave:"E accent grave",Eacute:"E accent aigue",Ecirc:"E accent circonflexe",Euml:"E trema",Igrave:"I accent grave",Iacute:"I accent aigue",Icirc:"I accent circonflexe",Iuml:"I trema",ETH:"Lettre majuscule islandaise ED",Ntilde:"N tilde",Ograve:"O accent grave",Oacute:"O accent aigue",Ocirc:"O accent circonflexe",Otilde:"O tilde",Ouml:"O trema",times:"Symbole de multiplication",Oslash:"O barre",Ugrave:"U accent grave",Uacute:"U accent aigue",
Ucirc:"U accent circonflexe",Uuml:"U trema",Yacute:"Y accent aigue",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a accent grave",aacute:"a accent aigue",acirc:"a accent circonflexe",atilde:"a tilde",auml:"a trema",aring:"a avec un cercle au dessus",aelig:"a",ccedil:"c cedille",egrave:"e accent grave",eacute:"e accent aigue",ecirc:"e accent circonflexe",euml:"e trema",igrave:"i accent grave",iacute:"i accent aigue",icirc:"i accent circonflexe",iuml:"i trema",
eth:"Lettre minuscule islandaise ED",ntilde:"n tilde",ograve:"o accent grave",oacute:"o accent aigue",ocirc:"O accent circonflexe",otilde:"O tilde",ouml:"O trema",divide:"Symbole de division",oslash:"o barre",ugrave:"u accent grave",uacute:"u accent aigue",ucirc:"u accent circonflexe",uuml:"u trema",yacute:"y accent aigue",thorn:"Lettre islandaise thorn minuscule",yuml:"y trema",OElig:"ligature majuscule latine Œ",oelig:"ligature minuscule latine œ",372:"W accent circonflexe",374:"Y accent circonflexe",
373:"w accent circonflexe",375:"y accent circonflexe",sbquo:"Guillemet simple fermant",8219:"Guillemet-virgule superieur culbute",bdquo:"Guillemet-virgule double inferieur",hellip:"Points de suspension",trade:"Symbole de marque deposee",9658:"Fleche noire pointant vers la droite",bull:"Puce",rarr:"Fleche vers la droite",rArr:"Fleche double vers la droite",hArr:"Fleche double vers la gauche",diams:"Carreau",asymp:"Presque egal"});