/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret cadratin",iexcl:"Point d'exclamation inverse",cent:"Symbole Cent",pound:"Symbole Livre Sterling",curren:"Symbole monetaire",yen:"Symbole Yen",brvbar:"Barre verticale scindee",sect:"Section",uml:"Trema",copy:"Symbole Copyright",ordf:"Indicateur ordinal feminin",laquo:"Guillemet francais ouvrant",
not:"Crochet de negation",reg:"Marque deposee",macr:"Macron",deg:"Degre",sup2:"Exposant 2",sup3:"\\tExposant 3",acute:"Accent aigu",micro:"Omicron",para:"Paragraphe",middot:"Point median",cedil:"Cedille",sup1:"\\tExposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet francais fermant",frac14:"Un quart",frac12:"Un demi",frac34:"Trois quarts",iquest:"Point d'interrogation inverse",Agrave:"A majuscule accent grave",Aacute:"A majuscule accent aigu",Acirc:"A majuscule accent circonflexe",Atilde:"A majuscule avec caron",
Auml:"A majuscule trema",Aring:"A majuscule avec un rond au-dessus",AElig:"A majuscule ligatures",Ccedil:"C majuscule cedille",Egrave:"E majuscule accent grave",Eacute:"E majuscule accent aigu",Ecirc:"E majuscule accent circonflexe",Euml:"E majuscule trema",Igrave:"I majuscule accent grave",Iacute:"I majuscule accent aigu",Icirc:"I majuscule accent circonflexe",Iuml:"I majuscule trema",ETH:"Lettre majuscule islandaise ED",Ntilde:"N majuscule avec caron",Ograve:"O majuscule accent grave",Oacute:"O majuscule accent aigu",
Ocirc:"O majuscule accent circonflexe",Otilde:"O majuscule avec caron",Ouml:"O majuscule trema",times:"Multiplication",Oslash:"O majuscule barre",Ugrave:"U majuscule accent grave",Uacute:"U majuscule accent aigu",Ucirc:"U majuscule accent circonflexe",Uuml:"U majuscule trema",Yacute:"Y majuscule accent aigu",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a minuscule accent grave",aacute:"a minuscule accent aigu",acirc:"a minuscule accent circonflexe",atilde:"a minuscule avec caron",
auml:"a minuscule trema",aring:"a minuscule avec un rond au-dessus",aelig:"a minuscule ligatures",ccedil:"c minuscule cedille",egrave:"e minuscule accent grave",eacute:"e minuscule accent aigu",ecirc:"e minuscule accent circonflexe",euml:"e minuscule trema",igrave:"i minuscule accent grave",iacute:"i minuscule accent aigu",icirc:"i minuscule accent circonflexe",iuml:"i minuscule trema",eth:"Lettre minuscule islandaise ED",ntilde:"n minuscule avec caron",ograve:"o minuscule accent grave",oacute:"o minuscule accent aigu",
ocirc:"o minuscule accent circonflexe",otilde:"o minuscule avec caron",ouml:"o minuscule trema",divide:"Division",oslash:"o minuscule barre",ugrave:"u minuscule accent grave",uacute:"u minuscule accent aigu",ucirc:"u minuscule accent circonflexe",uuml:"u minuscule trema",yacute:"y minuscule accent aigu",thorn:"Lettre islandaise thorn minuscule",yuml:"y minuscule trema",OElig:"ligature majuscule latine Œ",oelig:"ligature minuscule latine œ",372:"W majuscule accent circonflexe",374:"Y majuscule accent circonflexe",
373:"w minuscule accent circonflexe",375:"y minuscule accent circonflexe",sbquo:"Guillemet simple fermant (anglais)",8219:"Guillemet-virgule superieur culbute",bdquo:"Guillemet-virgule double inferieur",hellip:"Points de suspension",trade:"Marque commerciale (trade mark)",9658:"Fleche noire pointant vers la droite",bull:"Gros point median",rarr:"Fleche vers la droite",rArr:"Double fleche vers la droite",hArr:"Double fleche vers la gauche",diams:"Carreau noir",asymp:"Presque egal"});