/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","gl",{euro:"Simbolo do euro",lsquo:"Comina simple esquerda",rsquo:"Comina simple dereita",ldquo:"Cominas dobres esquerda",rdquo:"Cominas dobres dereita",ndash:"Guion",mdash:"Raia",iexcl:"Signo de admiracion invertido",cent:"Simbolo do centavo",pound:"Simbolo da libra",curren:"Simbolo de moeda",yen:"Simbolo do yen",brvbar:"Barra vertical rota",sect:"Simbolo de seccion",uml:"Dierese",copy:"Simbolo de dereitos de autoria",ordf:"Indicador ordinal feminino",laquo:"Cominas latinas, apertura",
not:"Signo negacion",reg:"Simbolo de marca rexistrada",macr:"Guion alto",deg:"Signo de grao",sup2:"Superindice dous",sup3:"Superindice tres",acute:"Acento agudo",micro:"Signo de micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"Superindice un",ordm:"Indicador ordinal masculino",raquo:"Cominas latinas, peche",frac14:"Fraccion ordinaria de un cuarto",frac12:"Fraccion ordinaria de un medio",frac34:"Fraccion ordinaria de tres cuartos",iquest:"Signo de interrogacion invertido",Agrave:"Letra A latina maiuscula con acento grave",
Aacute:"Letra A latina maiuscula con acento agudo",Acirc:"Letra A latina maiuscula con acento circunflexo",Atilde:"Letra A latina maiuscula con til",Auml:"Letra A latina maiuscula con dierese",Aring:"Letra A latina maiuscula con aro enriba",AElig:"Letra A latina maiuscula",Ccedil:"Letra C latina maiuscula con cedilla",Egrave:"Letra E latina maiuscula con acento grave",Eacute:"Letra E latina maiuscula con acento agudo",Ecirc:"Letra E latina maiuscula con acento circunflexo",Euml:"Letra E latina maiuscula con dierese",
Igrave:"Letra I latina maiuscula con acento grave",Iacute:"Letra I latina maiuscula con acento agudo",Icirc:"Letra I latina maiuscula con acento circunflexo",Iuml:"Letra I latina maiuscula con dierese",ETH:"Letra Ed latina maiuscula",Ntilde:"Letra N latina maiuscula con til",Ograve:"Letra O latina maiuscula con acento grave",Oacute:"Letra O latina maiuscula con acento agudo",Ocirc:"Letra O latina maiuscula con acento circunflexo",Otilde:"Letra O latina maiuscula con til",Ouml:"Letra O latina maiuscula con dierese",
times:"Signo de multiplicacion",Oslash:"Letra O latina maiuscula con barra transversal",Ugrave:"Letra U latina maiuscula con acento grave",Uacute:"Letra U latina maiuscula con acento agudo",Ucirc:"Letra U latina maiuscula con acento circunflexo",Uuml:"Letra U latina maiuscula con dierese",Yacute:"Letra Y latina maiuscula con acento agudo",THORN:"Letra Thorn latina maiuscula",szlig:"Letra s latina forte minuscula",agrave:"Letra a latina minuscula con acento grave",aacute:"Letra a latina minuscula con acento agudo",
acirc:"Letra a latina minuscula con acento circunflexo",atilde:"Letra a latina minuscula con til",auml:"Letra a latina minuscula con dierese",aring:"Letra a latina minuscula con aro enriba",aelig:"Letra a latina minuscula",ccedil:"Letra c latina minuscula con cedilla",egrave:"Letra e latina minuscula con acento grave",eacute:"Letra e latina minuscula con acento agudo",ecirc:"Letra e latina minuscula con acento circunflexo",euml:"Letra e latina minuscula con dierese",igrave:"Letra i latina minuscula con acento grave",
iacute:"Letra i latina minuscula con acento agudo",icirc:"Letra i latina minuscula con acento circunflexo",iuml:"Letra i latina minuscula con dierese",eth:"Letra ed latina minuscula",ntilde:"Letra n latina minuscula con til",ograve:"Letra o latina minuscula con acento grave",oacute:"Letra o latina minuscula con acento agudo",ocirc:"Letra o latina minuscula con acento circunflexo",otilde:"Letra o latina minuscula con til",ouml:"Letra o latina minuscula con dierese",divide:"Signo de division",oslash:"Letra o latina minuscula con barra transversal",
ugrave:"Letra u latina minuscula con acento grave",uacute:"Letra u latina minuscula con acento agudo",ucirc:"Letra u latina minuscula con acento circunflexo",uuml:"Letra u latina minuscula con dierese",yacute:"Letra y latina minuscula con acento agudo",thorn:"Letra Thorn latina minuscula",yuml:"Letra y latina minuscula con dierese",OElig:"Ligadura OE latina maiuscula",oelig:"Ligadura oe latina minuscula",372:"Letra W latina maiuscula con acento circunflexo",374:"Letra Y latina maiuscula con acento circunflexo",
373:"Letra w latina minuscula con acento circunflexo",375:"Letra y latina minuscula con acento circunflexo",sbquo:"Comina simple baixa, de apertura",8219:"Comina simple alta, de peche",bdquo:"Cominas dobres baixas, de apertura",hellip:"Elipse, puntos suspensivos",trade:"Signo de marca rexistrada",9658:"Apuntador negro apuntando a dereita",bull:"Vineta",rarr:"Frecha a dereita",rArr:"Frecha dobre a dereita",hArr:"Frecha dobre da esquerda a dereita",diams:"Diamante negro",asymp:"Case igual a"});