/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"Euro jel",lsquo:"Bal szimpla idezőjel",rsquo:"Jobb szimpla idezőjel",ldquo:"Bal dupla idezőjel",rdquo:"Jobb dupla idezőjel",ndash:"Rovid gondolatjel",mdash:"Hosszu gondolatjel",iexcl:"Forditott felkialtojel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"Hosszu kettőspont",sect:"Paragrafus jel",uml:"Kettős hangzo jel",copy:"Szerzői jog jel",ordf:"Női sorrend mutatoja",laquo:"Balra mutato duplanyil",not:"Felteteles kotőjel",
reg:"Bejegyzett vedjegy jele",macr:"Hosszusagi jel",deg:"Fok jel",sup2:"Negyzeten jel",sup3:"Kobon jel",acute:"Eles ekezet",micro:"Mikro-jel",para:"Bekezdes jel",middot:"Kozep pont",cedil:"Cedille",sup1:"Elsőn jel",ordm:"Ferfi sorrend mutatoja",raquo:"Jobbra mutato duplanyil",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"Harom negyed jel",iquest:"Forditott kerdőjel",Agrave:"Latin nagy A forditott ekezettel",Aacute:"Latin nagy A normal ekezettel",Acirc:"Latin nagy A hajtott ekezettel",Atilde:"Latin nagy A hullamjellel",
Auml:"Latin nagy A kettőspont ekezettel",Aring:"Latin nagy A gyűrű ekezettel",AElig:"Latin nagy A betű",Ccedil:"Latin nagy C cedillaval",Egrave:"Latin nagy E forditott ekezettel",Eacute:"Latin nagy E normal ekezettel",Ecirc:"Latin nagy E hajtott ekezettel",Euml:"Latin nagy E dupla kettőspont ekezettel",Igrave:"Latin nagy I forditott ekezettel",Iacute:"Latin nagy I normal ekezettel",Icirc:"Latin nagy I hajtott ekezettel",Iuml:"Latin nagy I kettőspont ekezettel",ETH:"Latin nagy Eth betű",Ntilde:"Latin nagy N hullamjellel",
Ograve:"Latin nagy O forditott ekezettel",Oacute:"Latin nagy O normal ekezettel",Ocirc:"Latin nagy O hajtott ekezettel",Otilde:"Latin nagy O hullamjellel",Ouml:"Latin nagy O kettőspont ekezettel",times:"Szorzas jel",Oslash:"Latin O betű athuzassal",Ugrave:"Latin nagy U forditott ekezettel",Uacute:"Latin nagy U normal ekezettel",Ucirc:"Latin nagy U hajtott ekezettel",Uuml:"Latin nagy U kettőspont ekezettel",Yacute:"Latin nagy Y normal ekezettel",THORN:"Latin nagy Thorn betű",szlig:"Latin kis s betű",
agrave:"Latin kis a forditott ekezettel",aacute:"Latin kis a normal ekezettel",acirc:"Latin kis a hajtott ekezettel",atilde:"Latin kis a hullamjellel",auml:"Latin kis a kettőspont ekezettel",aring:"Latin kis a gyűrű ekezettel",aelig:"Latin kis a betű",ccedil:"Latin kis c cedillaval",egrave:"Latin kis e forditott ekezettel",eacute:"Latin kis e normal ekezettel",ecirc:"Latin kis e hajtott ekezettel",euml:"Latin kis e dupla kettőspont ekezettel",igrave:"Latin kis i forditott ekezettel",iacute:"Latin kis i normal ekezettel",
icirc:"Latin kis i hajtott ekezettel",iuml:"Latin kis i kettőspont ekezettel",eth:"Latin kis eth betű",ntilde:"Latin kis n hullamjellel",ograve:"Latin kis o forditott ekezettel",oacute:"Latin kis o normal ekezettel",ocirc:"Latin kis o hajtott ekezettel",otilde:"Latin kis o hullamjellel",ouml:"Latin kis o kettőspont ekezettel",divide:"Osztasjel",oslash:"Latin kis o betű athuzassal",ugrave:"Latin kis u forditott ekezettel",uacute:"Latin kis u normal ekezettel",ucirc:"Latin kis u hajtott ekezettel",
uuml:"Latin kis u kettőspont ekezettel",yacute:"Latin kis y normal ekezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kettőspont ekezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott ekezettel",374:"Latin nagy Y hajtott ekezettel",373:"Latin kis w hajtott ekezettel",375:"Latin kis y hajtott ekezettel",sbquo:"Nyito nyomdai szimpla idezőjel",8219:"Zaro nyomdai zaro idezőjel",bdquo:"Nyito nyomdai dupla idezőjel",hellip:"Harom pont",trade:"Kereskedelmi vedjegy jele",
9658:"Jobbra mutato fekete mutato",bull:"Golyo",rarr:"Jobbra mutato nyil",rArr:"Jobbra mutato duplanyil",hArr:"Bal-jobb duplanyil",diams:"Fekete gyemant jel",asymp:"Majdnem egyenlő jel"});