/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt-br",{euro:"Euro",lsquo:"Aspas simples esquerda",rsquo:"Aspas simples direita",ldquo:"Aspas duplas esquerda",rdquo:"Aspas duplas direita",ndash:"Traco",mdash:"Travessao",iexcl:"Ponto de exclamacao invertido",cent:"Cent",pound:"Cerquilha",curren:"Dinheiro",yen:"Yen",brvbar:"Bara interrompida",sect:"Simbolo de Paragrafo",uml:"Trema",copy:"Direito de Copia",ordf:"Indicador ordinal feminino",laquo:"Aspas duplas angulares esquerda",not:"Negacao",reg:"Marca Registrada",
macr:"Macron",deg:"Grau",sup2:"2 Superscrito",sup3:"3 Superscrito",acute:"Acento agudo",micro:"Micro",para:"Pe de mosca",middot:"Ponto mediano",cedil:"Cedilha",sup1:"1 Superscrito",ordm:"Indicador ordinal masculino",raquo:"Aspas duplas angulares direita",frac14:"Um quarto",frac12:"Um meio",frac34:"Tres quartos",iquest:"Interrogacao invertida",Agrave:"A maiusculo com acento grave",Aacute:"A maiusculo com acento agudo",Acirc:"A maiusculo com acento circunflexo",Atilde:"A maiusculo com til",Auml:"A maiusculo com trema",
Aring:"A maiusculo com anel acima",AElig:"A maiusculo",Ccedil:"C maiulculo",Egrave:"E maiusculo com acento grave",Eacute:"E maiusculo com acento agudo",Ecirc:"E maiusculo com acento circumflexo",Euml:"E maiusculo com trema",Igrave:"I maiusculo com acento grave",Iacute:"I maiusculo com acento agudo",Icirc:"I maiusculo com acento circunflexo",Iuml:"I maiusculo com crase",ETH:"Eth maiusculo",Ntilde:"N maiusculo com til",Ograve:"O maiusculo com acento grave",Oacute:"O maiusculo com acento agudo",Ocirc:"O maiusculo com acento circunflexo",
Otilde:"O maiusculo com til",Ouml:"O maiusculo com trema",times:"Multiplicacao",Oslash:"Diametro",Ugrave:"U maiusculo com acento grave",Uacute:"U maiusculo com acento agudo",Ucirc:"U maiusculo com acento circunflexo",Uuml:"U maiusculo com trema",Yacute:"Y maiusculo com acento agudo",THORN:"Thorn maiusculo",szlig:"Eszett minusculo",agrave:"a minusculo com acento grave",aacute:"a minusculo com acento agudo",acirc:"a minusculo com acento circunflexo",atilde:"a minusculo com til",auml:"a minusculo com trema",
aring:"a minusculo com anel acima",aelig:"a minusculo",ccedil:"c minusculo",egrave:"e minusculo com acento grave",eacute:"e minusculo com acento agudo",ecirc:"e minusculo com acento circunflexo",euml:"e minusculo com trema",igrave:"i minusculo com acento grave",iacute:"i minusculo com acento agudo",icirc:"i minusculo com acento circunflexo",iuml:"i minusculo com trema",eth:"eth minusculo",ntilde:"n minusculo com til",ograve:"o minusculo com acento grave",oacute:"o minusculo com acento agudo",ocirc:"o minusculo com acento circunflexo",
otilde:"o minusculo com til",ouml:"o minusculo com trema",divide:"Divisao",oslash:"o minusculo com cortado ou diametro",ugrave:"u minusculo com acento grave",uacute:"u minusculo com acento agudo",ucirc:"u minusculo com acento circunflexo",uuml:"u minusculo com trema",yacute:"y minusculo com acento agudo",thorn:"thorn minusculo",yuml:"y minusculo com trema",OElig:"Ligacao tipografica OE maiuscula",oelig:"Ligacao tipografica oe minuscula",372:"W maiusculo com acento circunflexo",374:"Y maiusculo com acento circunflexo",
373:"w minusculo com acento circunflexo",375:"y minusculo com acento circunflexo",sbquo:"Aspas simples inferior direita",8219:"Aspas simples superior esquerda",bdquo:"Aspas duplas inferior direita",hellip:"Reticencias",trade:"Trade mark",9658:"Ponta de seta preta para direita",bull:"Ponto lista",rarr:"Seta para direita",rArr:"Seta dupla para direita",hArr:"Seta dupla direita e esquerda",diams:"Ouros",asymp:"Aproximadamente"});