/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt",{euro:"Simbolo do Euro",lsquo:"Aspa esquerda simples",rsquo:"Aspa direita simples",ldquo:"Aspa esquerda dupla",rdquo:"Aspa direita dupla",ndash:"Travessao Simples",mdash:"Travessao Longo",iexcl:"Ponto de exclamacao invertido",cent:"Simbolo do Centimo",pound:"Simbolo da Libra",curren:"Simbolo de Moeda",yen:"Simbolo do Iene",brvbar:"Barra quebrada",sect:"Simbolo de Seccao",uml:"Trema",copy:"Simbolo dos Direitos de Autor",ordf:"Indicador ordinal feminino",
laquo:"Aspa esquerda angulo duplo",not:"Nao Simbolo",reg:"Simbolo de Registado",macr:"Macron",deg:"Simbolo de Grau",sup2:"Expoente 2",sup3:"Expoente 3",acute:"Acento agudo",micro:"Simbolo de Micro",para:"Simbolo de Paragrafo",middot:"Ponto do Meio",cedil:"Cedilha",sup1:"Expoente 1",ordm:"Indicador ordinal masculino",raquo:"Aspas angulo duplo pra Direita",frac14:"Fracao vulgar 1/4",frac12:"Fracao vulgar 1/2",frac34:"Fracao vulgar 3/4",iquest:"Ponto de interrugacao invertido",Agrave:"Letra maiuscula latina A com acento grave",
Aacute:"Letra maiuscula latina A com acento agudo",Acirc:"Letra maiuscula latina A com circunflexo",Atilde:"Letra maiuscula latina A com til",Auml:"Letra maiuscula latina A com trema",Aring:"Letra maiuscula latina A com sinal diacritico",AElig:"Letra Maiuscula Latina A",Ccedil:"Letra maiuscula latina C com cedilha",Egrave:"Letra maiuscula latina E com acento grave",Eacute:"Letra maiuscula latina E com acento agudo",Ecirc:"Letra maiuscula latina E com circunflexo",Euml:"Letra maiuscula latina E com trema",
Igrave:"Letra maiuscula latina I com acento grave",Iacute:"Letra maiuscula latina I com acento agudo",Icirc:"Letra maiuscula latina I com cincunflexo",Iuml:"Letra maiuscula latina I com trema",ETH:"Letra maiuscula latina Eth (De)",Ntilde:"Letra maiuscula latina N com til",Ograve:"Letra maiuscula latina O com acento grave",Oacute:"Letra maiuscula latina O com acento agudo",Ocirc:"Letra maiuscula latina I com circunflexo",Otilde:"Letra maiuscula latina O com til",Ouml:"Letra maiuscula latina O com trema",
times:"Simbolo de Multiplicacao",Oslash:"Letra maiuscula O com barra",Ugrave:"Letra maiuscula latina U com acento grave",Uacute:"Letra maiuscula latina U com acento agudo",Ucirc:"Letra maiuscula latina U com circunflexo",Uuml:"Letra maiuscula latina E com trema",Yacute:"Letra maiuscula latina Y com acento agudo",THORN:"Letra maiuscula latina Runico",szlig:"Letra minuscula latina s forte",agrave:"Letra minuscula latina a com acento grave",aacute:"Letra minuscula latina a com acento agudo",acirc:"Letra minuscula latina a com circunflexo",
atilde:"Letra minuscula latina a com til",auml:"Letra minuscula latina a com trema",aring:"Letra minuscula latina a com sinal diacritico",aelig:"Letra minuscula latina a",ccedil:"Letra minuscula latina c com cedilha",egrave:"Letra minuscula latina e com acento grave",eacute:"Letra minuscula latina e com acento agudo",ecirc:"Letra minuscula latina e com circunflexo",euml:"Letra minuscula latina e com trema",igrave:"Letra minuscula latina i com acento grave",iacute:"Letra minuscula latina i com acento agudo",
icirc:"Letra minuscula latina i com circunflexo",iuml:"Letra pequena latina i com trema",eth:"Letra minuscula latina eth",ntilde:"Letra minuscula latina n com til",ograve:"Letra minuscula latina o com acento grave",oacute:"Letra minuscula latina o com acento agudo",ocirc:"Letra minuscula latina o com circunflexo",otilde:"Letra minuscula latina o com til",ouml:"Letra minuscula latina o com trema",divide:"Simbolo de Divisao",oslash:"Letra minuscula latina o com barra",ugrave:"Letra minuscula latina u com acento grave",
uacute:"Letra minuscula latina u com acento agudo",ucirc:"Letra minuscula latina u com circunflexo",uuml:"Letra minuscula latina u com trema",yacute:"Letra minuscula latina y com acento agudo",thorn:"Letra minuscula latina Runico",yuml:"Letra minuscula latina y com trema",OElig:"Ligadura maiuscula latina OE",oelig:"Ligadura minuscula latina oe",372:"Letra maiuscula latina W com circunflexo",374:"Letra maiuscula latina Y com circunflexo",373:"Letra minuscula latina w com circunflexo",375:"Letra minuscula latina y com circunflexo",
sbquo:"Aspa Simples inferior-9",8219:"Aspa Simples superior invertida-9",bdquo:"Aspa Duplas inferior-9",hellip:"Elipse Horizontal ",trade:"Simbolo de Marca Registada",9658:"Ponteiro preto direito",bull:"Marca",rarr:"Seta para a direita",rArr:"Seta dupla para a direita",hArr:"Seta dupla direita esquerda",diams:"Naipe diamante preto",asymp:"Quase igual a "});