/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"Ľava jednoducha uvodzovka",rsquo:"Prava jednoducha uvodzovka",ldquo:"Prava dvojita uvodzovka",rdquo:"Prava dvojita uvodzovka",ndash:"En pomlčka",mdash:"Em pomlčka",iexcl:"Obrateny vykričnik",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"Prerušena zvisla čiara",sect:"Znak odseku",uml:"Prehlaska",copy:"Znak copyrightu",ordf:"Žensky indikator rodu",laquo:"Znak dvojitych lomenych uvodzoviek vľavo",not:"Logisticky zapor",
reg:"Znak registracie",macr:"Pomlčka nad",deg:"Znak stupňa",sup2:"Dvojka ako horny index",sup3:"Trojka ako horny index",acute:"Dĺžeň",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost vľavo",sup1:"Jednotka ako horny index",ordm:"Mužsky indikator rodu",raquo:"Znak dvojitych lomenych uvodzoviek vpravo",frac14:"Obyčajny zlomok jedna štvrtina",frac12:"Obyčajny zlomok jedna polovica",frac34:"Obyčajny zlomok tri štvrtiny",iquest:"Otočeny otaznik",Agrave:"Veľke pismeno latinky A s accentom",
Aacute:"Veľke pismeno latinky A s dĺžňom",Acirc:"Veľke pismeno latinky A s makčeňom",Atilde:"Veľke pismeno latinky A s tildou",Auml:"Veľke pismeno latinky A s dvoma bodkami",Aring:"Veľke pismeno latinky A s kružkom nad",AElig:"Veľke pismeno latinky A",Ccedil:"Veľke pismeno latinky C s chvostom vľavo",Egrave:"Veľke pismeno latinky E s accentom",Eacute:"Veľke pismeno latinky E s dĺžňom",Ecirc:"Veľke pismeno latinky E s makčeňom",Euml:"Veľke pismeno latinky E s dvoma bodkami",Igrave:"Veľke pismeno latinky I s accentom",
Iacute:"Veľke pismeno latinky I s dĺžňom",Icirc:"Veľke pismeno latinky I s makčeňom",Iuml:"Veľke pismeno latinky I s dvoma bodkami",ETH:"Veľke pismeno latinky Eth",Ntilde:"Veľke pismeno latinky N s tildou",Ograve:"Veľke pismeno latinky O s accentom",Oacute:"Veľke pismeno latinky O s dĺžňom",Ocirc:"Veľke pismeno latinky O s makčeňom",Otilde:"Veľke pismeno latinky O s tildou",Ouml:"Veľke pismeno latinky O s dvoma bodkami",times:"Znak nasobenia",Oslash:"Veľke pismeno latinky O preškrtnute",Ugrave:"Veľke pismeno latinky U s accentom",
Uacute:"Veľke pismeno latinky U s dĺžňom",Ucirc:"Veľke pismeno latinky U s makčeňom",Uuml:"Veľke pismeno latinky U s dvoma bodkami",Yacute:"Veľke pismeno latinky Y s dĺžňom",THORN:"Veľke pismeno latinky Thorn",szlig:"Male pismeno latinky ostre s",agrave:"Male pismeno latinky a s accentom",aacute:"Male pismeno latinky a s dĺžňom",acirc:"Male pismeno latinky a s makčeňom",atilde:"Male pismeno latinky a s tildou",auml:"Male pismeno latinky a s dvoma bodkami",aring:"Male pismeno latinky a s kružkom nad",
aelig:"Male pismeno latinky a",ccedil:"Male pismeno latinky c s chvostom vľavo",egrave:"Male pismeno latinky e s accentom",eacute:"Male pismeno latinky e s dĺžňom",ecirc:"Male pismeno latinky e s makčeňom",euml:"Male pismeno latinky e s dvoma bodkami",igrave:"Male pismeno latinky i s accentom",iacute:"Male pismeno latinky i s dĺžňom",icirc:"Male pismeno latinky i s makčeňom",iuml:"Male pismeno latinky i s dvoma bodkami",eth:"Male pismeno latinky eth",ntilde:"Male pismeno latinky n s tildou",ograve:"Male pismeno latinky o s accentom",
oacute:"Male pismeno latinky o s dĺžňom",ocirc:"Male pismeno latinky o s makčeňom",otilde:"Male pismeno latinky o s tildou",ouml:"Male pismeno latinky o s dvoma bodkami",divide:"Znak delenia",oslash:"Male pismeno latinky o preškrtnute",ugrave:"Male pismeno latinky u s accentom",uacute:"Male pismeno latinky u s dĺžňom",ucirc:"Male pismeno latinky u s makčeňom",uuml:"Male pismeno latinky u s dvoma bodkami",yacute:"Male pismeno latinky y s dĺžňom",thorn:"Male pismeno latinky thorn",yuml:"Male pismeno latinky y s dvoma bodkami",
OElig:"Veľka ligatura latinky OE",oelig:"Mala ligatura latinky OE",372:"Veľke pismeno latinky W s makčeňom",374:"Veľke pismeno latinky Y s makčeňom",373:"Male pismeno latinky w s makčeňom",375:"Male pismeno latinky y s makčeňom",sbquo:"Dolna jednoducha 9-uvodzovka",8219:"Horna jednoducha otočena 9-uvodzovka",bdquo:"Dolna dvojita 9-uvodzovka",hellip:"Trojbodkovy uvod",trade:"Znak ibchodnej značky",9658:"Čierny ukazovateľ smerujuci vpravo",bull:"Kruh",rarr:"Šipka vpravo",rArr:"Dvojita šipka vpravo",
hArr:"Dvojita šipka vľavo a vpravo",diams:"Čierne piky",asymp:"Skoro sa rovna"});