/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sq",{euro:"Shenja e Euros",lsquo:"Thonjeza majtas me nje vi",rsquo:"Thonjeza djathtas me nje vi",ldquo:"Thonjeza majtas",rdquo:"Thonjeza djathtas",ndash:"En viza lidhese",mdash:"Em viza lidhese",iexcl:"Pikecuditese e permbysur",cent:"Shenja e Centit",pound:"Shejna e Funtit",curren:"Shenja e valutes",yen:"Shenja e Jenit",brvbar:"Viza e keputur",sect:"Shenja e pjeses",uml:"Diaeresis",copy:"Shenja e te drejtave te kopjimit",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Nuk ka shenje",reg:"Shenja e te regjistruarit",macr:"Macron",deg:"Shenja e shkalles",sup2:"Super-skripta dy",sup3:"Super-skripta tre",acute:"Theks i mprehte",micro:"Shjenja e Mikros",para:"Pilcrow sign",middot:"Pika e Mesme",cedil:"Hark nen shkronja",sup1:"Super-skripta nje",ordm:"Masculine ordinal indicator",raquo:"Right-pointing double angle quotation mark",frac14:"Thyesa nje te katrat",frac12:"Thyesa nje te dytat",frac34:"Thyesa tre te katrat",iquest:"Pikepyetje e permbysur",Agrave:"Shkronja e madhe latine A me theks te rende",
Aacute:"Shkronja e madhe latine A me theks akute",Acirc:"Shkronja e madhe latine A me theks lakor",Atilde:"Shkronja e madhe latine A me tilde",Auml:"Shkronja e madhe latine A me dy pika",Aring:"Shkronja e madhe latine A me unaze mbi",AElig:"Shkronja e madhe latine A",Ccedil:"Shkronja e madhe latine C me hark poshte",Egrave:"Shkronja e madhe latine E me theks te rende",Eacute:"Shkronja e madhe latine E me theks akute",Ecirc:"Shkronja e madhe latine E me theks lakor",Euml:"Shkronja e madhe latine E me dy pika",
Igrave:"Shkronja e madhe latine I me theks te rende",Iacute:"Shkronja e madhe latine I me theks akute",Icirc:"Shkronja e madhe latine I me theks lakor",Iuml:"Shkronja e madhe latine I me dy pika",ETH:"Shkronja e madhe latine Eth",Ntilde:"Shkronja e madhe latine N me tilde",Ograve:"Shkronja e madhe latine O me theks te rende",Oacute:"Shkronja e madhe latine O me theks akute",Ocirc:"Shkronja e madhe latine O me theks lakor",Otilde:"Shkronja e madhe latine O me tilde",Ouml:"Shkronja e madhe latine O me dy pika",
times:"Shenja e shumezimit",Oslash:"Shkronja e madhe latine O me vize ne mes",Ugrave:"Shkronja e madhe latine U me theks te rende",Uacute:"Shkronja e madhe latine U me theks akute",Ucirc:"Shkronja e madhe latine U me theks lakor",Uuml:"Shkronja e madhe latine U me dy pika",Yacute:"Shkronja e madhe latine Y me theks akute",THORN:"Shkronja e madhe latine Thorn",szlig:"Shkronja e voge latine s e mprehte",agrave:"Shkronja e voge latine a me theks te rende",aacute:"Shkronja e voge latine a me theks te mprehte",
acirc:"Shkronja e vogel latine a me theks lakor",atilde:"Shkronja e vogel latine a me tilde",auml:"Shkronja e vogel latine a me dy pika",aring:"Shkronja e voge latine a me unaze mbi",aelig:"Shkronja e voge latine a",ccedil:"Shkronja e vogel latine c me hark poshte",egrave:"Shkronja e voge latine e me theks te rende",eacute:"Shkronja e voge latine e me theks te mprehte",ecirc:"Shkronja e vogel latine e me theks lakor",euml:"Shkronja e vogel latine e me dy pika",igrave:"Shkronja e voge latine i me theks te rende",
iacute:"Shkronja e voge latine i me theks te mprehte",icirc:"Shkronja e vogel latine i me theks lakor",iuml:"Shkronja e vogel latine i me dy pika",eth:"Shkronja e voge latine eth",ntilde:"Shkronja e vogel latine n me tilde",ograve:"Shkronja e voge latine o me theks te rende",oacute:"Shkronja e voge latine o me theks te mprehte",ocirc:"Shkronja e vogel latine o me theks lakor",otilde:"Shkronja e vogel latine o me tilde",ouml:"Shkronja e vogel latine o me dy pika",divide:"Shenja ndarese",oslash:"Shkronja e vogel latine o me vize ne mes",
ugrave:"Shkronja e voge latine u me theks te rende",uacute:"Shkronja e voge latine u me theks te mprehte",ucirc:"Shkronja e vogel latine u me theks lakor",uuml:"Shkronja e vogel latine u me dy pika",yacute:"Shkronja e voge latine y me theks te mprehte",thorn:"Shkronja e vogel latine thorn",yuml:"Shkronja e vogel latine y me dy pika",OElig:"Shkronja e madhe e bashkuar latine OE",oelig:"Shkronja e vogel e bashkuar latine oe",372:"Shkronja e madhe latine W me theks lakor",374:"Shkronja e madhe latine Y me theks lakor",
373:"Shkronja e vogel latine w me theks lakor",375:"Shkronja e vogel latine y me theks lakor",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"Shenja e Simbolit Tregtare",9658:"Black right-pointing pointer",bull:"Pulla",rarr:"Shigjeta djathtas",rArr:"Shenja te dyfishta djathtas",hArr:"Shigjeta e dyfishe majtas-djathtas",diams:"Black diamond suit",asymp:"Gati e barabar me"});