/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro işareti",lsquo:"Sol tek tırnak işareti",rsquo:"Sağ tek tırnak işareti",ldquo:"Sol cift tırnak işareti",rdquo:"Sağ cift tırnak işareti",ndash:"En tire",mdash:"Em tire",iexcl:"Ters unlem işareti",cent:"Cent işareti",pound:"Pound işareti",curren:"Para birimi işareti",yen:"Yen işareti",brvbar:"Kırık bar",sect:"Bolum işareti",uml:"İki sesli harfin ayrılması",copy:"Telif hakkı işareti",ordf:"Dişil sıralı gosterge",laquo:"Sol-işaret cift acı tırnak işareti",
not:"Not işareti",reg:"Kayıtlı işareti",macr:"Makron",deg:"Derece işareti",sup2:"İkili ustsimge",sup3:"Uclu ustsimge",acute:"Aksan işareti",micro:"Mikro işareti",para:"Pilcrow işareti",middot:"Orta nokta",cedil:"Kedilla",sup1:"Ustsimge",ordm:"Eril sıralı gosterge",raquo:"Sağ işaret cift acı tırnak işareti",frac14:"Bayağı kesrin dortte biri",frac12:"Bayağı kesrin bir yarım",frac34:"Bayağı kesrin dortte uc",iquest:"Ters soru işareti",Agrave:"Aksanlı latin harfi",Aacute:"Aşırı aksanıyla Latin harfi",
Acirc:"Carpık Latin harfi",Atilde:"Tilde latin harfi",Auml:"Sesli harf ayrılımlıı latin harfi",Aring:"Halkalı latin buyuk A harfi",AElig:"Latin buyuk A harfi",Ccedil:"Latin buyuk C harfi ile kedilla",Egrave:"Aksanlı latin buyuk E harfi",Eacute:"Aşırı vurgulu latin buyuk E harfi",Ecirc:"Carpık latin buyuk E harfi",Euml:"Sesli harf ayrılımlıı latin buyuk E harfi",Igrave:"Aksanlı latin buyuk I harfi",Iacute:"Aşırı aksanlı latin buyuk I harfi",Icirc:"Carpık latin buyuk I harfi",Iuml:"Sesli harf ayrılımlıı latin buyuk I harfi",
ETH:"Latin buyuk Eth harfi",Ntilde:"Tildeli latin buyuk N harfi",Ograve:"Aksanlı latin buyuk O harfi",Oacute:"Aşırı aksanlı latin buyuk O harfi",Ocirc:"Carpık latin buyuk O harfi",Otilde:"Tildeli latin buyuk O harfi",Ouml:"Sesli harf ayrılımlı latin buyuk O harfi",times:"Carpma işareti",Oslash:"Vurgulu latin buyuk O harfi",Ugrave:"Aksanlı latin buyuk U harfi",Uacute:"Aşırı aksanlı latin buyuk U harfi",Ucirc:"Carpık latin buyuk U harfi",Uuml:"Sesli harf ayrılımlı latin buyuk U harfi",Yacute:"Aşırı aksanlı latin buyuk Y harfi",
THORN:"Latin buyuk Thorn harfi",szlig:"Latin kucuk keskin s harfi",agrave:"Aksanlı latin kucuk a harfi",aacute:"Aşırı aksanlı latin kucuk a harfi",acirc:"Carpık latin kucuk a harfi",atilde:"Tildeli latin kucuk a harfi",auml:"Sesli harf ayrılımlı latin kucuk a harfi",aring:"Halkalı latin kucuk a harfi",aelig:"Latin buyuk a harfi",ccedil:"Kedillalı latin kucuk c harfi",egrave:"Aksanlı latin kucuk e harfi",eacute:"Aşırı aksanlı latin kucuk e harfi",ecirc:"Carpık latin kucuk e harfi",euml:"Sesli harf ayrılımlı latin kucuk e harfi",
igrave:"Aksanlı latin kucuk i harfi",iacute:"Aşırı aksanlı latin kucuk i harfi",icirc:"Carpık latin kucuk i harfi",iuml:"Sesli harf ayrılımlı latin kucuk i harfi",eth:"Latin kucuk eth harfi",ntilde:"Tildeli latin kucuk n harfi",ograve:"Aksanlı latin kucuk o harfi",oacute:"Aşırı aksanlı latin kucuk o harfi",ocirc:"Carpık latin kucuk o harfi",otilde:"Tildeli latin kucuk o harfi",ouml:"Sesli harf ayrılımlı latin kucuk o harfi",divide:"Bolme işareti",oslash:"Vurgulu latin kucuk o harfi",ugrave:"Aksanlı latin kucuk u harfi",
uacute:"Aşırı aksanlı latin kucuk u harfi",ucirc:"Carpık latin kucuk u harfi",uuml:"Sesli harf ayrılımlı latin kucuk u harfi",yacute:"Aşırı aksanlı latin kucuk y harfi",thorn:"Latin kucuk thorn harfi",yuml:"Sesli harf ayrılımlı latin kucuk y harfi",OElig:"Latin buyuk bağlı OE harfi",oelig:"Latin kucuk bağlı oe harfi",372:"Carpık latin buyuk W harfi",374:"Carpık latin buyuk Y harfi",373:"Carpık latin kucuk w harfi",375:"Carpık latin kucuk y harfi",sbquo:"Tek duşuk-9 tırnak işareti",8219:"Tek yuksek-ters-9 tırnak işareti",
bdquo:"Cift duşuk-9 tırnak işareti",hellip:"Yatay elips",trade:"Marka tescili işareti",9658:"Siyah sağ işaret işaretcisi",bull:"Koyu nokta",rarr:"Sağa doğru ok",rArr:"Sağa doğru cift ok",hArr:"Sol, sağ cift ok",diams:"Siyah elmas takımı",asymp:"Hemen hemen eşit"});