/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","vi",{euro:"Ky hiệu Euro",lsquo:"Dấu ngoặc đơn trai",rsquo:"Dấu ngoặc đơn phải",ldquo:"Dấu ngoặc đoi trai",rdquo:"Dấu ngoặc đoi phải",ndash:"Gạch ngang tiếng anh",mdash:"Gạch ngang Em",iexcl:"Chuyển đổi dấu chấm than",cent:"Ky tự tiền Mỹ",pound:"Ky tự tiền Anh",curren:"Ky tự tiền tệ",yen:"Ky tự tiền Yen Nhật",brvbar:"Thanh hỏng",sect:"Ky tự khu vực",uml:"Dấu tach đoi",copy:"Ky tự bản quyền",ordf:"Phần chỉ thị giống cai",laquo:"Chọn dấu ngoặc đoi trai",not:"Khong co ky tự",
reg:"Ky tự đăng ky",macr:"Dấu nguyen am dai",deg:"Ky tự độ",sup2:"Chữ trồi len tren dạng 2",sup3:"Chữ trồi len tren dạng 3",acute:"Dấu trọng am",micro:"Ky tự micro",para:"Ky tự đoạn văn",middot:"Dấu chấm tron",cedil:"Dấu moc lưới",sup1:"Ky tự trồi len cấp 1",ordm:"Ky tự biểu hiện giống đực",raquo:"Chọn dấu ngoặc đoi phải",frac14:"Tỉ lệ một phần tư",frac12:"Tỉ lệ một nửa",frac34:"Tỉ lệ ba phần tư",iquest:"Chuyển đổi dấu chấm hỏi",Agrave:"Ky tự la-tinh viết hoa A với dấu huyền",Aacute:"Ky tự la-tinh viết hoa A với dấu sắc",
Acirc:"Ky tự la-tinh viết hoa A với dấu mũ",Atilde:"Ky tự la-tinh viết hoa A với dấu nga",Auml:"Ky tự la-tinh viết hoa A với dấu hai chấm tren đầu",Aring:"Ky tự la-tinh viết hoa A với biểu tượng vong tron tren đầu",AElig:"Ky tự la-tinh viết hoa của A",Ccedil:"Ky tự la-tinh viết hoa C với dấu moc ben dưới",Egrave:"Ky tự la-tinh viết hoa E với dấu huyền",Eacute:"Ky tự la-tinh viết hoa E với dấu sắc",Ecirc:"Ky tự la-tinh viết hoa E với dấu mũ",Euml:"Ky tự la-tinh viết hoa E với dấu hai chấm tren đầu",
Igrave:"Ky tự la-tinh viết hoa I với dấu huyền",Iacute:"Ky tự la-tinh viết hoa I với dấu sắc",Icirc:"Ky tự la-tinh viết hoa I với dấu mũ",Iuml:"Ky tự la-tinh viết hoa I với dấu hai chấm tren đầu",ETH:"Viết hoa của ky tự Eth",Ntilde:"Ky tự la-tinh viết hoa N với dấu nga",Ograve:"Ky tự la-tinh viết hoa O với dấu huyền",Oacute:"Ky tự la-tinh viết hoa O với dấu sắc",Ocirc:"Ky tự la-tinh viết hoa O với dấu mũ",Otilde:"Ky tự la-tinh viết hoa O với dấu nga",Ouml:"Ky tự la-tinh viết hoa O với dấu hai chấm tren đầu",
times:"Ky tự phep toan nhan",Oslash:"Ky tự la-tinh viết hoa A với dấu nga xuống",Ugrave:"Ky tự la-tinh viết hoa U với dấu huyền",Uacute:"Ky tự la-tinh viết hoa U với dấu sắc",Ucirc:"Ky tự la-tinh viết hoa U với dấu mũ",Uuml:"Ky tự la-tinh viết hoa U với dấu hai chấm tren đầu",Yacute:"Ky tự la-tinh viết hoa Y với dấu sắc",THORN:"Phần viết hoa của ky tự Thorn",szlig:"Ky tự viết nhỏ la-tinh của chữ s",agrave:"Ky tự la-tinh thường với dấu huyền",aacute:"Ky tự la-tinh thường với dấu sắc",acirc:"Ky tự la-tinh thường với dấu mũ",
atilde:"Ky tự la-tinh thường với dấu nga",auml:"Ky tự la-tinh thường với dấu hai chấm tren đầu",aring:"Ky tự la-tinh viết thường với biểu tượng vong tron tren đầu",aelig:"Ky tự la-tinh viết thường của a",ccedil:"Ky tự la-tinh viết thường của c với dấu moc ben dưới",egrave:"Ky tự la-tinh viết thường e với dấu huyền",eacute:"Ky tự la-tinh viết thường e với dấu sắc",ecirc:"Ky tự la-tinh viết thường e với dấu mũ",euml:"Ky tự la-tinh viết thường e với dấu hai chấm tren đầu",igrave:"Ky tự la-tinh viết thường i với dấu huyền",
iacute:"Ky tự la-tinh viết thường i với dấu sắc",icirc:"Ky tự la-tinh viết thường i với dấu mũ",iuml:"Ky tự la-tinh viết thường i với dấu hai chấm tren đầu",eth:"Ky tự la-tinh viết thường của eth",ntilde:"Ky tự la-tinh viết thường n với dấu nga",ograve:"Ky tự la-tinh viết thường o với dấu huyền",oacute:"Ky tự la-tinh viết thường o với dấu sắc",ocirc:"Ky tự la-tinh viết thường o với dấu mũ",otilde:"Ky tự la-tinh viết thường o với dấu nga",ouml:"Ky tự la-tinh viết thường o với dấu hai chấm tren đầu",
divide:"Ky hiệu phep tinh chia",oslash:"Ky tự la-tinh viết thường o với dấu nga",ugrave:"Ky tự la-tinh viết thường u với dấu huyền",uacute:"Ky tự la-tinh viết thường u với dấu sắc",ucirc:"Ky tự la-tinh viết thường u với dấu mũ",uuml:"Ky tự la-tinh viết thường u với dấu hai chấm tren đầu",yacute:"Ky tự la-tinh viết thường y với dấu sắc",thorn:"Ky tự la-tinh viết thường của chữ thorn",yuml:"Ky tự la-tinh viết thường y với dấu hai chấm tren đầu",OElig:"Ky tự la-tinh viết hoa gạch nối OE",oelig:"Ky tự la-tinh viết thường gạch nối OE",
372:"Ky tự la-tinh viết hoa W với dấu mũ",374:"Ky tự la-tinh viết hoa Y với dấu mũ",373:"Ky tự la-tinh viết thường w với dấu mũ",375:"Ky tự la-tinh viết thường y với dấu mũ",sbquo:"Dấu ngoặc đơn thấp số-9",8219:"Dấu ngoặc đơn đảo ngược số-9",bdquo:"Gấp đoi dấu ngoặc đơn số-9",hellip:"Tĩnh dược chiều ngang",trade:"Ky tự thương hiệu",9658:"Ky tự trỏ về hướng ben phải mau đen",bull:"Ky hiệu",rarr:"Mũi ten hướng ben phải",rArr:"Mũi ten hướng ben phải dạng đoi",hArr:"Mũi ten hướng ben trai dạng đoi",diams:"Ky hiệu hinh thoi",
asymp:"Gần bằng với"});